version: '3.7'
services:

     
        
     web:
        container_name: nginx
        image: nginx
        ports:
        - 80:80
        - 443:443
        volumes:
           - ./nginx/conf.d:/etc/nginx/conf.d
           - ./nginx/certs:/etc/ssl/certs
           - ./php:/var/www/html
        links:
           - fpm
        restart: always

     database:
        container_name: mysql
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        ports:
          - 3306:3306
        restart: always
        volumes:
          - ./mysql:/var/lib/mysql
        environment:
                MYSQL_ROOT_PASSWORD: password
                MYSQL_USER: wordpress
                MYSQL_PASSWORD: password
                MYSQL_DATABASE: wordpress

     fpm:
        container_name: php
        image: wordpress:fpm
        restart: always
        environment:
                WORDPRESS_DB_HOST: database:3306
                WORDPRESS_DB_USER: wordpress
                WORDPRESS_DB_PASSWORD: password
                WORDPRESS_DB_NAME: wordpress
        ports:
                - 9000:9000
        volumes:
          - ./php:/var/www/html
          - ./datavolume:/etc/php-fpm.d
        links:
          - database

